<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\NodeType;

/**
 * Implements hook_theme().
 */
function blog_theme($existing, $type, $theme, $path) {
  return [
    'blog_previous_next' => [
      'variables' => [
        'entity' => NULL,
      ],
      'file' => 'blog.theme.inc',
    ],
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function blog_entity_extra_field_info() {
  $extra = [];

  // Вернет все типы материалов которые созданы (Запись в блог, Страница)
  foreach (NodeType::loadMultiple() as $bundle) {
    $extra['node'][$bundle->id()]['display']['previous_next'] = [
      'label' => t('Buttons to previous and next entity'),
      'weight' => 100,
      'visible' => FALSE,
    ];
  }

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function blog_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('previous_next')) {
    $build['previous_next'] = [
      '#theme' => 'blog_previous_next',
      '#entity' => $node,
    ];
  }
}